[SofaPython3] Add a LinkPath object in both the binding and plugin.
sofa-framework/SofaPython3 pull request #265
Opened 2022-06-09 10:57 UTC by damienmarchal

This PR is following the discussion in #197 

The existing syntax to make links in SofaPython3 is the following one:
```python
node.addObject("MeshObjLoader", name="loader")
node.addObject("MechanicalObject", position=node.loader.position.getLinkPath())
```

In addition to be very verbose the getLinkPath() is returning a string (eg: "@/node/loader.position").
Representing linkpath with string has the drawback of forcing the two objects to be part of the same simulation graph which is not always the case.

Example of code that does not work as expected:
```python
def MyPrefab(target):
	node = Sofa.Core.Node("MyPrefab")
	node.addObject("MeshObjLoader", name="loader")
	node2.addObject("MechanicalObject", position=target)
	return node

def createScene(root):
	root.addObject("MeshObjLoader", name="loader")
	root.addChild( MyPrefab(loader.position.getLinkPath()) )
```

It does not work because string returned by getLinkPath() is a path query into the scene-graph to locate the object or the data
field to attach not into the one of the graph the destination object is. 

To solve this issue this PR introduce a LinkPath object which is dedicated to point to a sofa object.
This LinkPath object is exposed in python and can be used to make parenting between objects and data without the need of graph to path then path to graph conversion (so it is also much faster.. but we don't really care here right ?).

For consistency with the "value" in data field the PR expose the LinkPath with a dedicated "linkpath" attribute.
So the code is now the following:
```python
root.addObject("MeshObjLoader", name="loader")
root.addChild("MechanicalObject", name="p1", position=root.loader.position.value)      # Copy the value
root.addChild("MechanicalObject", name="p2", position=root.loader.position.linkpath)   # Make a link between data without the need for string based query

root.addObject("Mapping", name="loader", input=p1.linkpath)
```

2022-06-21 08:34 UTC, damienmarchal commented
This PR really deserve some attention :)

2022-06-21 13:28 UTC, alxbilger requested changes

2022-06-21 13:28 UTC, alxbilger commented on bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Node.cpp
> +    // For each argument of the addObject functin we check if this is a
```suggestion
    // For each argument of the addObject function we check if this is a
```
I think the sentence is not finished

2022-06-21 13:28 UTC, alxbilger commented on bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Node.cpp
> +    }
```suggestion
    for(auto [key, value] : dict)
    {
        if(py::isinstance<LinkPath>(value))
        {
            auto* data = self->findData(py::str(key));
            if(data)
                BindingBase::SetData(data, py::cast<py::object>(value));

            auto* link = self->findLink(py::str(key));
            if(link)
                BindingBase::SetLink(link, py::cast<py::object>(value));
        }
    }
```

This suggestion using a structured binding is not mandatory, but I think it's a case where it helps the reading

2022-06-21 21:12 UTC, damienmarchal commented on Plugin/src/SofaPython3/LinkPath.cpp
> +        targetBase = target->getOwner();
Thank for pointing this. The condition is not needed.

2022-06-22 08:27 UTC, alxbilger commented on bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Node.cpp
> +    }
I don't see this as resolved

2022-06-22 10:56 UTC, damienmarchal commented
If we agree this is the new API yes it is very easy to deprecate getLinkPath...but this will emit a lot of warning in every python scene. So I recommend deprecating the getLinkPath() thing for 22.12

2022-06-22 11:11 UTC, damienmarchal commented on bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Node.cpp
> +    // For each argument of the addObject functin we check if this is a
DIdn't had commited the suggestion ?

2022-06-28 07:15 UTC, damienmarchal commented
@hugtalbot so what ?

2022-06-29 09:10 UTC, damienmarchal commented
This PR is adding a new feature linkpath that is a "non string" approach to make link between data or objects. 
The PR was proposed to implement the conclusion of https://github.com/sofa-framework/SofaPython3/issues/197 
The issue 197 wanted being explicit 
```python
node.addObject("toto", position=otherObject.position.linkpath)  # makes a link without path conversion explicitely
node.addObject("toto", position=otherObject.position.value)  # makes a copy to initialize
```
instead of: 
```python
node.addObject("toto", position=otherObject.position)  # makes a link without path conversion implicitely
node.addObject("toto", position=otherObject.position.value)  # makes a copy to initialize
```

Hugo suggested to deprecate getLinkPath()... I'm not sure it is the proper PR to do that because it is not wise to deprecate a long standing feature by a modernized replacement. 

But I see two options:
- JérémieA pointed that in InSimo's fork they are using "path" in place of "getLinkPath()". It may be wise to replace getLinkPath()
In that case  "myobject.linkpath" and "myobject.path" are not returning the same thing. And modernizing the examples are:

```python
# The existing 
 # makes a link with a stringyfied path (so generation and parse) and to work this imply being in the same graph for path resolution suceed at init and so on). 
node.addObject("toto", position=position.getLinkPaht()) 

# This version (from InSimo) is strictly equivalent to getLinkPath (same drawbacks) except that it use a python attribute to make the syntax more "slick"... we may want to go to such a thing  
node.addObject("toto", position=position.path)  

# This version (from the PR) is *not* a replacement of getLinkPath it is superset. 
node.addObject("toto", position=position.linkpath)  # makes a link without path conversion
print("This is a to link object", position.linkpath) 
node.addObject("toto", position=str(position.linkpath))  # makes a link with path conversion
print("This is the link representation as a path", str(position.linkpath)) 
```

2022-07-12 08:01 UTC, damienmarchal commented
Hi @hugtalbot, thank for pointing I will look at that after the release.

2022-08-16 08:24 UTC, merged