Xp readthedocs
sofa-framework/SofaPython3 pull request #352
Opened 2023-06-07 14:08 UTC by damienmarchal

2023-09-13 13:18 UTC, damienmarchal commented
Hi Hugo do we go for a merge ?

2023-09-15 10:24 UTC, alxbilger commented
@hugtalbot ready to merge?

It seems there is failing unit test. Not sure it is related to this PR though

2023-09-26 00:41 UTC, fredroy requested changes

2023-09-26 00:41 UTC, fredroy commented on Plugin/src/SofaPython3/Prefab.cpp
> +    sofa::simulation::getSimulation()->init(this);
This is a revert of https://github.com/sofa-framework/SofaPython3/pull/357

I think this branch must be rebased on the current master

2024-09-13 14:51 UTC, closed without merging