[CI] Update workflow to match branch name
sofa-framework/SofaPython3 pull request #414
Opened 2024-05-28 08:49 UTC by bakpaul

2024-07-16 05:55 UTC, fredroy requested changes

2024-07-16 05:55 UTC, fredroy commented on .github/workflows/ci.yml
> +        sofa_branch: [v24.06]        python_version: ['3.10']
```suggestion
        sofa_branch: [v24.06]        
        python_version: ['3.10']
```

2024-09-13 08:26 UTC, damienmarchal commented
What is the status of this PR ?

2024-10-17 11:17 UTC, damienmarchal commented
Hi @bakpaul, what is the status of this PR ?

2025-01-08 13:10 UTC, closed without merging